#!/bin/bash

MYNAME="$0"; # standard boilerplate: where I am?

case "$0" in
    /*) ;;
   */*) MYNAME="$(/bin/pwd)/$MYNAME" ;;
     *) MYNAME="$(which "$MYNAME")" ;;
esac

MYPATH="$(dirname $MYNAME)"

. $MYPATH/scripts/profile-tools.shlib

begin_profile "$@"
{
    :
    add_to_path PATH          "$MYPATH/misc"  "$MYPATH/scripts" "$MYPATH/bin"
    add_to_path MKLIB_PATH    "$MYPATH/mklib"
    add_to_path PYTHONPATH    "$MYPATH/pylib"
    # add_to_path EMACSLOADPATH "$MYPATH/elisp"

    # add_to_path PYTHONPATH  "$MYPATH"
}
end_profile
