#!/bin/bash

# LDS-Tools2: A collection of useful scripts developed by M E Leypold
# Copyright (C) 2013 -- M E Leypold

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Profile: This is the eval style profile for lsd-tools2. To pull it in, 
# write 'eval "$(/path/to/project/Profile)"' in you .bash_profile.

MYNAME="$0";                      # standard boilerplate: where I am?

case "$0" in
    /*) ;;
   */*) MYNAME="$(/bin/pwd)/$MYNAME" ;;
     *) MYNAME="$(which "$MYNAME")" ;;
esac

MYPATH="$(dirname $MYNAME)"

. $MYPATH/scripts/profile-tools.shlib

begin_profile "$@"
{
    :
    add_to_path PATH          "$MYPATH/mklib" "$MYPATH/misc"  "$MYPATH/scripts" "$MYPATH/bin" "$MYPATH/orx" \
                              "$MYPATH/legacy" "$MYPATH/generix"
    add_to_path MKLIB_PATH    "$MYPATH/mklib"
    add_to_path PYTHONPATH    "$MYPATH/pylib"
}
end_profile

