#!/bin/sh
#
#   lsdscripts -- miscellanous useful utilities
#
#   Copyright (C) 2006-2009  M E Leypold
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   version 2 as published by the Free Software Foundation (no later
#   version).
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
#   02110-1301 USA.
#
#
#   stx-find-include -- inclusion path resolver for stx (see there)

. lsdtools.shlib

if test -z "$STX_INCLUDEPATH"; then
   STX_INCLUDEPATH='.'
fi

for F in "$@"; do
    path_search -f "$F" $( echo "$STX_INCLUDEPATH" | sed 's|[ :][ :]*| |g' )
    if test "$?" -gt 0; then panic "not found: $F." ; fi
done

